services:
  - type: web
    name: employee-task-management
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn employee_task_mgmt.wsgi
    envVars:
      - key: SECRET_KEY
        value: 'django-insecure-$)jynyv86j8o*w1v&1aku3*7)q(!wfrowr!eo22s*l2(_7f)5q'
      - key: DEBUG
        value: "False"
